### ISSUE TITLE
Linkt ot /give page

### ISSUE THREAD

**Issue by iff11** [MichalBryxi/minimalismu.cz#1]
Výzva, O co jde, Daruj zisk chybí doplnit odkaz, pravděpodobně má vést do http://30dni.minimalismu.cz/#/engage/give

screen: http://www.awesomescreenshot.com/image/793898/1986f669ea5f80abc2201e199d3dd341

**Comment by MichalBryxi** [comment]
Fixed, thanks!

**Comment by iff11** [comment]
ok
