### ISSUE TITLE
Event na rozprodej zbytků

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/minimalismu.cz#12]
Dobrý den, na leden už akce spravuji já a chtěla jsem se zeptat, jestli už víte jak to bude se závěrečnou dražbou věcí na 30 dní minimalismu?

5 ledna od 18:00, šlo by?

Ano šlo. Mohl by jste mi prosím k tomu akorát potom poslat krátkou anotaci, popř.i fotku?

**Comment by MichalBryxi** [comment]
Ping @iff_11

**Comment by iff11** [comment]
@MichalBryxi můžeš mi napsat od koho ti to přišlo?

**Comment by MichalBryxi** [comment]
@iff11 Tahle holčina: https://www.facebook.com/misa.v.martinkova

**Comment by iff11** [comment]
hotovo, Misel poslán tenhle text:
Zakončení akce Pošli to dál aneb #30dníminimalismu

přijď na neformální posezení! Má to cenu, pokud tě zajímá aspoň jeden z následujících bodů:
- vyhlášení konečné částky, která se vybrala po dobu trvání akce "Pošli to dál a přispěj na dobrou věc aneb #30dníMinimalismu"
-  debata o vlastních zkušenostech při třídění svého "šumu"
- příležitost, kdy si vyzvednout balíček, který na tebe čeká pod piánem v kavárně
- pokus o dražbu kousků, co se naschromáždily v offline verzi v kavárně
- řekni nám svůj názor- písemná anonymní anketa
- otázky a pokus o odpovědi k tématu
