### ISSUE TITLE
Link to "online platby"

### ISSUE THREAD

**Issue by iff11** [MichalBryxi/minimalismu.cz#3]
Výzva, Jak na to, Prodávající dá peníze ... Druhý link v odstavci vede na home, nezapomenout dát tam správný odkaz 
screen: http://www.awesomescreenshot.com/image/793931/34ed55ea710a47a5cd6fdf67c027c55f

**Comment by MichalBryxi** [comment]
Fixed in: https://github.com/MichalBryxi/minimalismu.cz/commit/39b79fe1e956d89b6c09d9a598c5e58a3690d15d

**Comment by iff11** [comment]
ok
